test/forge/MarketParamsLibTest.sol

There shouldn't be any more after that:
`grep -R -e "\(from\|import\) \"[^\.]" test/forge/ src/`

Remove last absolute import

---

test/forge/integration/LiquidateIntegrationTest.sol

[Reference](https://discord.com/channels/1072909701601308672/1155839514862964808/1162277843447853097)
I think we did not notice this since the amount of assets is lower than the number of shares and so here the `Math.min()` was capping the maximum number of shares to repay to a lower value.

Calculate correct amount of shares

---

test/forge/integration/LiquidateIntegrationTest.sol

it was a simple one but I ended up refactoring it to avoid stack too deep and harmonize both tests

test(liquidate): dont realize bad debt

---

src/interfaces/IMorpho.sol
src/libraries/periphery/MorphoBalancesLib.sol

- Fixes https://github.com/cantinasec/review-morpho-blue-1/issues/63

Document possible conversion reverts

---

src/Morpho.sol
src/interfaces/IMorpho.sol
test/forge/BaseTest.sol
test/forge/integration/AccrueInterestIntegrationTest.sol
test/forge/libraries/periphery/MorphoBalancesLibTest.sol

Fixes #129 
BBT tree is already up to date

Add public accrue interest function

---

src/Morpho.sol
test/forge/integration/LiquidateIntegrationTest.sol

- Fixes #https://github.com/cantinasec/review-morpho-blue-1/issues/58

`UtilsLib.zeroFloorSub` is not utilised consistently

---

foundry.toml
test/forge/invariant/MorphoInvariantTest.sol
test/forge/libraries/periphery/MorphoBalancesLibTest.sol

temporary, because there is a problem somewhere

chore: remove invariants in CI

---

src/Morpho.sol
src/interfaces/IMorpho.sol
test/forge/integration/CreateMarketIntegrationTest.sol
test/forge/libraries/periphery/MorphoStorageLibTest.sol

This is something we have missed in #567

Signature of `idToMarketParams` to return a struct

---

src/Morpho.sol
src/interfaces/IMorpho.sol
src/interfaces/IMorphoCallbacks.sol
src/mocks/FlashBorrowerMock.sol
test/forge/integration/CallbacksIntegrationTest.sol

Adds return bytes to the flash loan callback and the flash loan function so a callback user can pass data back to itself without using storage.

Add return bytes to flashloan callback

---

src/Morpho.sol
src/libraries/periphery/MorphoBalancesLib.sol
src/mocks/IrmMock.sol

I think that we should remove the IRM call skip bacause (https://github.com/morpho-org/morpho-blue/issues/460):
- it makes building IRMs more complex (the dev has to think about this)
- it creates some weird cases in our first IRM (https://github.com/morpho-labs/morpho-blue-irm/pull/54#discussion_r1380565416)
- we have in mind not so crazy scenarios where one might want to do something particular when a market stayed empty of with only supply for a certain period of time (that actually includes my second point) (https://github.com/morpho-org/morpho-blue/issues/460#issue-1875682799)
- it simplifies Morpho Blue
- we don't care about this opti, interacting with a market without any borrow is super rare
- https://github.com/cantinasec/review-morpho-blue-1/issues/42

Remove IRM call skip

---

src/interfaces/IMorpho.sol

docs: document reset share price jump

---

certora/specs/Liveness.spec
src/Morpho.sol

[Certora] mutant 6

---

certora/specs/Liveness.spec
src/Morpho.sol

[Certora] mutant 10

---

certora/specs/Liveness.spec
src/Morpho.sol

[Certora] mutant 3

---

test/forge/integration/LiquidateIntegrationTest.sol

This PR tests the computation to make sure that a borrow position is safe (if nothing changes) for a period `elapsed`

Add liquidate margin test

---

certora/README.md
certora/gambit.conf
certora/specs/AccrueInterest.spec
certora/specs/ConsistentState.spec
certora/specs/ExactMath.spec
certora/specs/ExitLiquidity.spec
certora/specs/Health.spec
certora/specs/LibSummary.spec
certora/specs/Liveness.spec
certora/specs/RatioMath.spec
certora/specs/Reentrancy.spec
certora/specs/Reverts.spec

Improve the verification based on the following list of mutants:
- #603 
- #617 
- #616
- #615
- #614 
- #613 
- #612 
- #611 
- #610
- #609
- #608 
- #607 
- #606 
- #605
- #604

[Certora] Mutations

---

certora/specs/RatioMath.spec

Check that the supply ratio for liquidate increases when no bad debt has been realized. This fixes one of the "improve rules" points in #390

[Certora] Supply ratio for liquidate

---

src/libraries/periphery/MorphoBalancesLib.sol

docs(ifc): add edge case

---

src/Morpho.sol
src/libraries/periphery/MorphoBalancesLib.sol
test/forge/BaseTest.sol
test/forge/integration/AccrueInterestIntegrationTest.sol
test/forge/integration/CreateMarketIntegrationTest.sol
test/forge/integration/OnlyOwnerIntegrationTest.sol
test/hardhat/Morpho.spec.ts
tsconfig.json

- Fixes #631 
it takes 85k gas to create an idle market while it takes 175k gas to create a standard market
and here is the gas diff between standard markets (left) and idle markets (right):
on avg, it costs -9k to supply/withdraw to/from an idle market

feat(irm): skip address(0)

---

certora/confs/AccrueInterest.conf
certora/confs/AssetsAccounting.conf
certora/confs/ConsistentState.conf
certora/confs/ExactMath.conf
certora/confs/Health.conf
certora/confs/LibSummary.conf
certora/confs/Liveness.conf
certora/confs/RatioMath.conf
certora/confs/Reentrancy.conf
certora/confs/Reverts.conf
certora/confs/Transfer.conf
src/Morpho.sol

See the review of #638 for more details

Rounding liquidate fix

---

certora/README.md

Just realized that there was discrepancy between the README and the specification files. This change is needed for the communication on the formal verification of Blue

Certora README small fix

---

src/Morpho.sol
test/forge/integration/AuthorizationIntegrationTest.sol

- Fixes https://github.com/morpho-org/morpho-blue/pull/630#discussion_r1430371174

fix(authorization): revert already set error

---

certora/harness/MorphoHarness.sol
certora/specs/ConsistentState.spec

This PR completes the invariant about `idToMarketParams`. This invariant is splitted into 2 Certora invariants (`hashOfMarketParams` and `marketParamsOfHash`), and states that: `idToMarketParams()` and `id()` are reciprocal functions, under the condition that the corresponding market has been created

[Certora] Complete the idToMarketParams invariant

---

.github/workflows/certora.yml
certora/confs/AccrueInterest.conf
certora/confs/AssetsAccounting.conf
certora/confs/ConsistentState.conf
certora/confs/ExactMath.conf
certora/confs/Health.conf
certora/confs/LibSummary.conf
certora/confs/Liveness.conf
certora/confs/RatioMath.conf
certora/confs/Reentrancy.conf
certora/confs/Reverts.conf
certora/confs/Transfer.conf
certora/specs/ConsistentState.spec
certora/specs/Reverts.spec

What it does:
- mandatory update to remove the keyword `STORAGE`
- specialize solc version, to make it easier to work with multiple projects (can always be overriden on the CLI)
- use struct comparison directly in CVL, instead of comparing the fields

[Certora] Update CVL version 7.0.7

---

test/forge/BaseTest.sol
test/forge/invariant/MorphoInvariantTest.sol

Fixes:
- #680 
- [now it is possible](https://github.com/foundry-rs/foundry/issues/4190) to `vm.assume` in invariants

Improve bounds in tests

---

test/forge/invariant/MorphoInvariantTest.sol

Use the exact calculation of Morpho Blue to compute the amount to deal when liquidating in the invariants.
Fixes:
- #682

Precise dealt amount liquidate

---

certora/README.md

fix: typos

---

certora/specs/AssetsAccounting.spec
certora/specs/ExactMath.spec

Improve assets accounting specification so that we don't have to assume that supply, borrow, and supplyCollateral start with an empty position

[Certora] Improve assets accounting specification

---

test/halmos/HalmosTest.sol

this updates halmos tests for the new version.
changes:
- replaced --symbolic-storage with enableSymbolicStorage() cheatcode
- explicitly updated the block number and timestamp
- fixed and improved calldata generation for flashLoan()

test: update halmos tests for new version

---

test/forge/BaseTest.sol
test/forge/invariant/MorphoInvariantTest.sol

This PR:
- fixes, in [f178c58](https://github.com/morpho-org/morpho-blue/pull/695/commits/f178c5876f40ea26f540ef6189fa9e85f919debb),  the computation of `repaidAssets` in `_liquidateSeizedAssets`, where interest not being accrued can underestimate it. Note that then it would potentially revert with "insufficient balance" in the following `liquidate`. 
<details><summary> See failing test to add to <tt>MorphoInvariantTest.sol</tt> </summary>
```solidity
function testPreciseRepaidAssets() public {
bool success;
vm.prank(USER);
(success,) = address(this).call(
abi.encodeCall(
this.supplySharesOnBehalfNoRevert,
(
12120140710833733770211937208572361813353,
115792089237316195423570985008687907853269984665640564039457584007913129639932,
47864507797463465527
)
)
);
require(success); …
```

Tests: fix CI with precise computations

---

certora/confs/AccrueInterest.conf
certora/confs/AssetsAccounting.conf
certora/confs/ConsistentState.conf
certora/confs/ExactMath.conf
certora/confs/ExchangeRate.conf
certora/confs/Health.conf
certora/confs/LibSummary.conf
certora/confs/Liveness.conf
certora/confs/Reentrancy.conf
certora/confs/Reverts.conf
certora/confs/StayHealthy.conf
certora/confs/Transfer.conf
certora/specs/Health.spec

This PR:
- removes the unnecessary `priceChanged = false` in the spec. This is not necessary because we assume that `priceChanged` is false at the end, and the only way it can change is by being set to true
- removes the setting `cache` to `none` in `ExactMath.conf`, which was there as an artifact of an old timeout
- formats the conf files according to Prettier rules for JSON files
- solves a timeout in StayHealthyLiquidate that was coming back at every new CVL release

[Certora] Quick refactor

---

certora/confs/AccrueInterest.conf
certora/confs/AssetsAccounting.conf
certora/confs/ConsistentState.conf
certora/confs/ExactMath.conf
certora/confs/ExchangeRate.conf
certora/confs/Health.conf
certora/confs/LibSummary.conf
certora/confs/Liveness.conf
certora/confs/Reverts.conf
certora/confs/StayHealthy.conf
certora/harness/MorphoHarness.sol
certora/harness/Util.sol
certora/specs/AccrueInterest.spec
certora/specs/AssetsAccounting.spec
certora/specs/ConsistentState.spec
certora/specs/ExactMath.spec
certora/specs/ExchangeRate.spec
certora/specs/Health.spec
certora/specs/LibSummary.spec
certora/specs/Liveness.spec
certora/specs/Reverts.spec
certora/specs/StayHealthy.spec

- What
This PR adds missing getter for verification and externalizes several useful functions.
- Why
The missing getters to return `Market` and `Position` could simplify verification in other projects, as well a generic `Util` library could improve clarity.
- How
The getters are implemented on the `MorphoHarness` and a dedicated `Util.sol` file is added to externalize generic functions.
Fixes #699.

[Certora] Improve utility functions access

---

certora/README.md

I reviewed the entire repository, no more typos found in docs. 
Hope this helps streamline the project!
Best regards,
Bilogweb3

chore: correct typos docs

---

certora/specs/Reverts.spec

It was missing from the Reverts specification

Add flashLoan input validation

---

src/interfaces/IMorpho.sol

docs: improve wording of assumptions for liveness

---

certora/confs/StayHealthy.conf

This spec times out from time to time : see second commit CI run to see that. The fix is in third commit. 
The `"cache" : "none"` was added to show that it fixes the issue (otherwise it always goes through thanks to the cache)

Fix stay healthy liquidate rule depending on cache

---

funding.json

We need to do this to verify the repo for OP retroactive funding.

Add verifier for OP funding

---

certora/confs/StayHealthy.conf
certora/specs/ExactMath.spec
certora/specs/Health.spec
certora/specs/StayHealthy.spec

This PR:
- removes summarization of mulDiv that was not needed
- simplifies the summarization of the oracle, that was essentially always used as a constant
- removes the assumption about summaryMulDiv in specs

[Certora] Simplify summarization of mulDiv and price

---

certora/specs/AccrueInterest.spec
certora/specs/ExchangeRate.spec
certora/specs/Health.spec
certora/specs/LiquidateBuffer.spec
certora/specs/Reentrancy.spec
src/interfaces/IMorpho.sol

Max assets supplied and borrowed should be ~1e32, because starting at 1e33 this corresponds to 1e39 shares and log2(1e39) ~= 129.5 > 128

Document max assets
