morpho-org/morpho-blue

tsconfig.json
feel free to merge it if you approve
=> build(tsconfig): update to standard

src/Morpho.sol, test/forge/integration/OnlyOwnerIntegrationTest.sol
Fixes https://github.com/cantinasec/review-morpho-blue-1/issues/34
=> Emit owner at deployment

src/interfaces/IMorpho.sol
- Fixes https://github.com/cantinasec/review-morpho-blue-1/issues/44
- Fixes https://github.com/cantinasec/review-morpho-blue-1/issues/43
=> Clarify fee recipient documentation

src/interfaces/IMorpho.sol
- Fixes https://github.com/cantinasec/review-morpho-blue-1/issues/45
=> Acknowledge EIP-3156 non compliance

src/libraries/periphery/MorphoBalancesLib.sol, test/forge/BaseTest.sol, test/forge/libraries/periphery/MorphoBalancesLibTest.sol
- Fixes https://github.com/cantinasec/review-morpho-blue-1/issues/52
=> Rename expected balance for assets

src/interfaces/IMorpho.sol
Fixes https://github.com/cantinasec/review-morpho-blue-1/issues/41
=> Funds could be stuck if IRM reverts

src/Morpho.sol, src/interfaces/IMorpho.sol, src/libraries/periphery/MorphoBalancesLib.sol, test/forge/BaseTest.sol, test/forge/libraries/periphery/MorphoLibTest.sol
- Fixes #555 
- Fixes https://github.com/cantinasec/review-morpho-blue-1/issues/51
=> Refactor interfaces

package.json
- Fixes https://github.com/typicode/husky/issues/1146
=> fix(package): replace postinstall with prepare

src/interfaces/IMorpho.sol
https://github.com/cantinasec/review-morpho-blue-1/issues/40
=> docs: document inflation attack (spearbit 40)

certora/specs/Liveness.spec, src/Morpho.sol
=> [Certora] mutant 2

certora/specs/Reverts.spec, src/Morpho.sol
=> [Certora] mutant 13

certora/specs/AccrueInterest.spec, certora/specs/ConsistentState.spec, certora/specs/ExactMath.spec, certora/specs/ExitLiquidity.spec, certora/specs/Health.spec, certora/specs/LibSummary.spec, certora/specs/Liveness.spec, certora/specs/RatioMath.spec, certora/specs/Reentrancy.spec, certora/specs/Reverts.spec, src/Morpho.sol
=> [Certora] mutant 12

certora/confs/AccrueInterest.conf, certora/specs/AccrueInterest.spec, src/Morpho.sol
Fixes :
- #647 
Also adds an optimization of the `lastUpdate` variable when not needing to be updated
=> [Certora] Accrue interest fix

test/forge/integration/CreateMarketIntegrationTest.sol
Fixes foundry crashing when trying to mock Cheatcode address calls
=> test(irm): dont fuzz irm

test/forge/BaseTest.sol, test/forge/InvariantTest.sol, test/forge/invariant/BaseMorphoInvariantTest.sol, test/forge/invariant/MorphoDynamicInvariantTest.sol, test/forge/invariant/MorphoStaticInvariantTest.sol
=> test(invariant): re-implement lost invariants

.github/workflows/npm-release.yml, package.json
=> fix(ci): fix npm-release action

certora/specs/ConsistentState.spec, certora/specs/Health.spec, certora/specs/Liveness.spec, certora/specs/Reentrancy.spec, certora/specs/Reverts.spec, certora/specs/Transfer.spec
Fixes CI not passing (see last run on main) because of the update of the Certora prover to version 6
=> [Certora] Update to v6 of the prover

.github/workflows/certora.yml, certora/confs/ExactMath.conf, foundry.toml
=> [Certora] fix exact math timeout

certora/confs/LibSummary.conf
Halmos tests will be fixed in #692
=> [Certora] New syntax for enabling bitvector theory

certora/confs/StayHealthy.conf
Fix timeout on StayHealthy that would appear at each new version of CVL
=> Fix StayHealthy timeout
